apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: ai-service
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: lumiai-env
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
