name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # OIDC 토큰 생성을 위해 필요

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'  # Maven 의존성 캐시

      - name: Build with Maven
        run: mvn --batch-mode clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to OCI Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCIR_REGISTRY }}
          username: ${{ secrets.OCIR_USERNAME }}
          password: ${{ secrets.OCIR_TOKEN }}

      - name: Generate Image Tag
        id: image-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="${{ secrets.OCIR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.image-tag.outputs.tag }}
            ${{ secrets.OCIR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure kubectl for OKE
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Verify Cluster Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Update Kubernetes Secrets
        run: |
          kubectl delete secret lumiai-env --ignore-not-found=true
          kubectl create secret generic lumiai-env \
            --from-literal=GEMINI_API_KEY='${{ secrets.GEMINI_API_KEY }}' \
            --from-literal=GOOGLE_MAPS_API_KEY='${{ secrets.GOOGLE_MAPS_API_KEY }}'

      - name: Update Deployment Image
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ steps.image-tag.outputs.tag }}|g" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/lumiai-app --timeout=300s

      - name: Verify Deployment
        run: |
          kubectl get pods -l app=lumiai-app
          kubectl get services
